http:
  middlewares:
    feedback-ratelimit:
      rateLimit:
        average: 10
        period: 1m
        burst: 5
        sourceCriterion:
          ipStrategy:
            depth: 1

    secure-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        stsSeconds: 31536000
        stsIncludeSubdomains: true
